service:
  name: udacity-todo-app
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-west-1'}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
